# Generated by Django 5.1.7 on 2025-03-31 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0005_mensaje_curso_asociado_alter_alumno_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='tipo',
            field=models.CharField(default='Sin tipo', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nota',
            name='calificacion',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('TEA', 'TEA'), ('TEP', 'TEP'), ('TED', 'TED')], max_length=3),
        ),
    ]
