# Generated by Django 5.1.7 on 2025-05-15 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0006_nota_tipo_alter_nota_calificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('curso', models.CharField(choices=[('1A', '1°A'), ('1B', '1°B'), ('2A', '2°A'), ('2B', '2°B'), ('3A', '3°A'), ('3B', '3°B'), ('4ECO', '4° Economía'), ('4NAT', '4° Naturales'), ('5ECO', '5° Economía'), ('5NAT', '5° Naturales'), ('6ECO', '6° Economía'), ('6NAT', '6° Naturales')], max_length=10)),
                ('tipo_evento', models.CharField(choices=[('evaluacion', 'Evaluación'), ('entrega', 'Entrega de TP'), ('otro', 'Otro')], max_length=50)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
