# Generated by Django 5.1.7 on 2025-05-15 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0007_evento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='hora',
        ),
    ]
