# Generated by Django 5.1.7 on 2025-05-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0008_remove_evento_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='cuatrimestre',
            field=models.IntegerField(choices=[(1, '1er cuatrimestre'), (2, '2do cuatrimestre')], default=1),
        ),
    ]
