# Generated by Django 5.1.7 on 2025-05-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0009_nota_cuatrimestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='tipo',
            field=models.CharField(choices=[('evaluacion', 'Evaluación'), ('tp', 'Trabajo Práctico'), ('oral', 'Oral'), ('recuperatorio', 'Recuperatorio')], max_length=20),
        ),
    ]
