# Generated by Django 5.1.7 on 2025-06-03 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0010_alter_nota_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('presente', models.BooleanField(default=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calificaciones.alumno')),
            ],
            options={
                'unique_together': {('alumno', 'fecha')},
            },
        ),
    ]
