# Generated by Django 5.1.7 on 2025-09-01 23:28

import calificaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0013_alumno_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='calificacion',
            field=models.CharField(max_length=15, validators=[calificaciones.models.validate_calificacion_ext]),
        ),
    ]
