# Generated by Django 5.1.7 on 2025-09-01 23:58

import calificaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0014_alter_nota_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='calificacion',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('TEA', 'TEA'), ('TEP', 'TEP'), ('TED', 'TED'), ('NO ENTREGADO', 'No entregado')], max_length=15, validators=[calificaciones.models.validate_calificacion_ext]),
        ),
    ]
