# Generated by Django 5.1.7 on 2025-09-02 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0015_alter_nota_calificacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistencia',
            options={'ordering': ['-fecha', 'alumno_id']},
        ),
        migrations.AlterModelOptions(
            name='nota',
            options={'ordering': ['alumno_id', 'cuatrimestre', 'fecha']},
        ),
        migrations.AddIndex(
            model_name='asistencia',
            index=models.Index(fields=['alumno', 'fecha'], name='calificacio_alumno__a26721_idx'),
        ),
        migrations.AddIndex(
            model_name='nota',
            index=models.Index(fields=['alumno', 'cuatrimestre'], name='calificacio_alumno__2b52a6_idx'),
        ),
        migrations.AddIndex(
            model_name='nota',
            index=models.Index(fields=['alumno', 'materia'], name='calificacio_alumno__af843f_idx'),
        ),
    ]
