# Generated by Django 5.1.7 on 2025-09-02 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0016_alter_asistencia_options_alter_nota_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(blank=True, choices=[('1A', '1°A'), ('1B', '1°B'), ('2A', '2°A'), ('2B', '2°B'), ('3A', '3°A'), ('3B', '3°B'), ('4ECO', '4° Economía'), ('4NAT', '4° Naturales'), ('5ECO', '5° Economía'), ('5NAT', '5° Naturales'), ('6ECO', '6° Economía'), ('6NAT', '6° Naturales')], max_length=10, null=True)),
                ('fecha', models.DateField()),
                ('asunto', models.CharField(max_length=120)),
                ('mensaje', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanciones', to='calificaciones.alumno')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', 'alumno_id', '-id'],
                'indexes': [models.Index(fields=['alumno', 'fecha'], name='calificacio_alumno__daa89c_idx'), models.Index(fields=['curso', 'fecha'], name='calificacio_curso_de4f35_idx')],
            },
        ),
    ]
