# Generated by Django 5.1.7 on 2025-09-09 20:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0017_sancion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensaje',
            options={'ordering': ['-fecha_envio', '-id']},
        ),
        migrations.AddField(
            model_name='mensaje',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas', to='calificaciones.mensaje'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='thread_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['receptor', 'fecha_envio'], name='calificacio_recepto_e49048_idx'),
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['emisor', 'fecha_envio'], name='calificacio_emisor__f8599f_idx'),
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['thread_id', 'fecha_envio'], name='calificacio_thread__b8dddc_idx'),
        ),
    ]
