# Generated by Django 5.1.7 on 2025-09-13 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0019_backfill_thread_ids'),
        ('calificaciones', '0019_mensaje_leido_flags'),
    ]

    operations = [
    ]
