# Generated by Django 5.1.7 on 2025-09-22 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0020_merge_20250913_1736'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreceptorCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(choices=[('1A', '1°A'), ('1B', '1°B'), ('2A', '2°A'), ('2B', '2°B'), ('3A', '3°A'), ('3B', '3°B'), ('4ECO', '4° Economía'), ('4NAT', '4° Naturales'), ('5ECO', '5° Economía'), ('5NAT', '5° Naturales'), ('6ECO', '6° Economía'), ('6NAT', '6° Naturales')], db_index=True, max_length=20)),
                ('asignado_en', models.DateTimeField(auto_now_add=True)),
                ('preceptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación de curso a preceptor',
                'verbose_name_plural': 'Asignaciones de cursos a preceptores',
                'indexes': [models.Index(fields=['curso'], name='calificacio_curso_515a71_idx'), models.Index(fields=['preceptor'], name='calificacio_precept_8a9fc3_idx')],
                'unique_together': {('preceptor', 'curso')},
            },
        ),
    ]
