# Generated by Django 5.1.7 on 2025-12-29 03:50

import calificaciones.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0024_backfill_alumno_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_envio', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='asistencia',
            options={'ordering': ['-fecha', '-id']},
        ),
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['-fecha', '-id']},
        ),
        migrations.AlterModelOptions(
            name='nota',
            options={'ordering': ['-fecha', '-id']},
        ),
        migrations.AlterModelOptions(
            name='sancion',
            options={'ordering': ['-fecha', '-id']},
        ),
        migrations.RemoveIndex(
            model_name='asistencia',
            name='calificacio_alumno__a26721_idx',
        ),
        migrations.RemoveIndex(
            model_name='mensaje',
            name='calificacio_recepto_e49048_idx',
        ),
        migrations.RemoveIndex(
            model_name='mensaje',
            name='calificacio_emisor__f8599f_idx',
        ),
        migrations.RemoveIndex(
            model_name='mensaje',
            name='calificacio_thread__b8dddc_idx',
        ),
        migrations.RemoveIndex(
            model_name='nota',
            name='calificacio_alumno__2b52a6_idx',
        ),
        migrations.RemoveIndex(
            model_name='nota',
            name='calificacio_alumno__af843f_idx',
        ),
        migrations.RemoveIndex(
            model_name='sancion',
            name='calificacio_alumno__daa89c_idx',
        ),
        migrations.RemoveIndex(
            model_name='sancion',
            name='calificacio_curso_de4f35_idx',
        ),
        migrations.RenameField(
            model_name='mensaje',
            old_name='receptor',
            new_name='destinatario',
        ),
        migrations.RenameField(
            model_name='mensaje',
            old_name='emisor',
            new_name='remitente',
        ),
        migrations.RenameField(
            model_name='sancion',
            old_name='mensaje',
            new_name='motivo',
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='curso_asociado',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='leido_en',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='reply_to',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='thread_id',
        ),
        migrations.RemoveField(
            model_name='sancion',
            name='asunto',
        ),
        migrations.RemoveField(
            model_name='sancion',
            name='creado_en',
        ),
        migrations.RemoveField(
            model_name='sancion',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='sancion',
            name='curso',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='tipo_asistencia',
            field=models.CharField(choices=[('clases', 'Clases'), ('informatica', 'Informática'), ('catequesis', 'Catequesis')], db_index=True, default='clases', max_length=20),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='curso',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='tipo_remitente',
            field=models.CharField(choices=[('Profesor', 'Profesor'), ('Preceptor', 'Preceptor'), ('Directivo', 'Directivo')], default='Profesor', max_length=20),
        ),
        migrations.AddField(
            model_name='nota',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sancion',
            name='detalle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sancion',
            name='docente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sancion',
            name='tipo',
            field=models.CharField(choices=[('Amonestación', 'Amonestación'), ('Llamado de atención', 'Llamado de atención'), ('Suspensión', 'Suspensión')], default='Amonestación', max_length=50),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='apellido',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='curso',
            field=models.CharField(choices=[('1A', '1A'), ('1B', '1B'), ('2A', '2A'), ('2B', '2B'), ('3A', '3A'), ('3B', '3B'), ('4A', '4A'), ('4B', '4B'), ('5A', '5A'), ('5B', '5B'), ('6A', '6A'), ('6B', '6B'), ('4ECO', '4ECO'), ('4NAT', '4NAT'), ('5ECO', '5ECO'), ('5NAT', '5NAT'), ('6ECO', '6ECO'), ('6NAT', '6NAT')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='id_alumno',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='observacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='curso',
            field=models.CharField(choices=[('1A', '1A'), ('1B', '1B'), ('2A', '2A'), ('2B', '2B'), ('3A', '3A'), ('3B', '3B'), ('4A', '4A'), ('4B', '4B'), ('5A', '5A'), ('5B', '5B'), ('6A', '6A'), ('6B', '6B'), ('4ECO', '4ECO'), ('4NAT', '4NAT'), ('5ECO', '5ECO'), ('5NAT', '5NAT'), ('6ECO', '6ECO'), ('6NAT', '6NAT')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo_evento',
            field=models.CharField(choices=[('Evaluación', 'Evaluación'), ('Entrega', 'Entrega'), ('Acto', 'Acto'), ('Reunión', 'Reunión'), ('Otro', 'Otro')], default='Otro', max_length=50),
        ),
        migrations.AlterField(
            model_name='evento',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='asunto',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='leido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='nota',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='calificaciones.alumno'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='calificacion',
            field=models.CharField(max_length=15, validators=[calificaciones.models.validate_calificacion_ext]),
        ),
        migrations.AlterField(
            model_name='nota',
            name='cuatrimestre',
            field=models.IntegerField(choices=[(1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='nota',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='nota',
            name='materia',
            field=models.CharField(choices=[('Lengua', 'Lengua'), ('Matemática', 'Matemática'), ('Ciencias', 'Ciencias'), ('Historia', 'Historia'), ('Geografía', 'Geografía'), ('Inglés', 'Inglés'), ('Educación Física', 'Educación Física'), ('Música', 'Música'), ('Plástica', 'Plástica'), ('Catequesis', 'Catequesis'), ('Informática', 'Informática')], max_length=50),
        ),
        migrations.AlterField(
            model_name='nota',
            name='tipo',
            field=models.CharField(choices=[('Examen', 'Examen'), ('Trabajo Práctico', 'Trabajo Práctico'), ('Participación', 'Participación'), ('Tarea', 'Tarea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='preceptorcurso',
            name='curso',
            field=models.CharField(choices=[('1A', '1A'), ('1B', '1B'), ('2A', '2A'), ('2B', '2B'), ('3A', '3A'), ('3B', '3B'), ('4A', '4A'), ('4B', '4B'), ('5A', '5A'), ('5B', '5B'), ('6A', '6A'), ('6B', '6B'), ('4ECO', '4ECO'), ('4NAT', '4NAT'), ('5ECO', '5ECO'), ('5NAT', '5NAT'), ('6ECO', '6ECO'), ('6NAT', '6NAT')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sancion',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='asistencia',
            index=models.Index(fields=['alumno', 'fecha', 'tipo_asistencia'], name='calificacio_alumno__5b2b00_idx'),
        ),
        migrations.AddConstraint(
            model_name='asistencia',
            constraint=models.UniqueConstraint(fields=('alumno', 'fecha', 'tipo_asistencia'), name='unique_asistencia_alumno_fecha_tipo'),
        ),
        migrations.AddField(
            model_name='comunicado',
            name='remitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
