# Generated by ChatGPT on 2026-01-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0025_comunicado_alter_asistencia_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='tarde',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddConstraint(
            model_name='asistencia',
            constraint=models.CheckConstraint(
                check=models.Q(('tarde', False), ('presente', True), _connector='OR'),
                name='asistencia_tarde_requiere_presente',
            ),
        ),
    ]
