# Generated by ChatGPT on 2026-01-05
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calificaciones", "0026_asistencia_tarde"),
    ]

    operations = [
        migrations.AddField(
            model_name="asistencia",
            name="justificada",
            field=models.BooleanField(default=False, db_index=True),
        ),
        migrations.AddConstraint(
            model_name="asistencia",
            constraint=models.CheckConstraint(
                check=(models.Q(justificada=False) | models.Q(presente=False) | models.Q(tarde=True)),
                name="asistencia_justificada_requiere_ausente_o_tarde",
            ),
        ),
    ]
