# Generated by ChatGPT on 2026-01-13
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ("calificaciones", "0027_asistencia_justificada"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tipo", models.CharField(choices=[("nota", "Nota"), ("sancion", "Sanción"), ("asistencia", "Asistencia"), ("mensaje", "Mensaje"), ("otro", "Otro")], db_index=True, default="otro", max_length=30)),
                ("titulo", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("url", models.CharField(blank=True, max_length=500, null=True)),
                ("creada_en", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("leida", models.BooleanField(db_index=True, default=False)),
                ("meta", models.JSONField(blank=True, null=True)),
                ("destinatario", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="notificaciones", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-creada_en", "-id"],
            },
        ),
    ]
