# Generated by Django 5.1.7 on 2026-01-16 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0029_alter_notificacion_options_alumno_usuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('nota', 'Nota'), ('sancion', 'Sanción'), ('inasistencia', 'Inasistencia'), ('mensaje', 'Mensaje'), ('evento', 'Evento'), ('otro', 'Otro')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='ProfesorCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(choices=[('1A', '1A'), ('1B', '1B'), ('2A', '2A'), ('2B', '2B'), ('3A', '3A'), ('3B', '3B'), ('4A', '4A'), ('4B', '4B'), ('5A', '5A'), ('5B', '5B'), ('6A', '6A'), ('6B', '6B'), ('4ECO', '4ECO'), ('4NAT', '4NAT'), ('5ECO', '5ECO'), ('5NAT', '5NAT'), ('6ECO', '6ECO'), ('6NAT', '6NAT')], db_index=True, max_length=20)),
                ('asignado_en', models.DateTimeField(auto_now_add=True)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_asignados_profesor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación de curso a profesor',
                'verbose_name_plural': 'Asignaciones de cursos a profesores',
                'indexes': [models.Index(fields=['curso'], name='calificacio_curso_85b8a6_idx'), models.Index(fields=['profesor'], name='calificacio_profeso_70de53_idx')],
                'unique_together': {('profesor', 'curso')},
            },
        ),
    ]
