# Generated by Django 5.1.7 on 2026-03-03 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calificaciones", "0031_unique_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="nota",
            name="nota_numerica",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AddField(
            model_name="nota",
            name="resultado",
            field=models.CharField(
                blank=True,
                choices=[("TEA", "Aprobado"), ("TEP", "Desaprobado"), ("TED", "Aplazado")],
                db_index=True,
                max_length=3,
                null=True,
            ),
        ),
    ]
