# Generated by Django 5.1.7 on 2026-03-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0032_nota_nota_numerica_nota_resultado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='tipo_asistencia',
            field=models.CharField(choices=[('clases', 'Clases'), ('informatica', 'Informática'), ('catequesis', 'Catequesis')], db_index=True, default='clases', max_length=20),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo_evento',
            field=models.CharField(choices=[('Evaluación', 'Evaluación'), ('Entrega', 'Entrega'), ('Acto', 'Acto'), ('Reunión', 'Reunión'), ('Otro', 'Otro')], default='Otro', max_length=50),
        ),
        migrations.AlterField(
            model_name='nota',
            name='materia',
            field=models.CharField(choices=[('Lengua', 'Lengua'), ('Matemática', 'Matemática'), ('Ciencias', 'Ciencias'), ('Historia', 'Historia'), ('Geografía', 'Geografía'), ('Inglés', 'Inglés'), ('Educación Física', 'Educación Física'), ('Música', 'Música'), ('Plástica', 'Plástica'), ('Catequesis', 'Catequesis'), ('Informática', 'Informática')], max_length=50),
        ),
        migrations.AlterField(
            model_name='nota',
            name='tipo',
            field=models.CharField(choices=[('Examen', 'Examen'), ('Trabajo Práctico', 'Trabajo Práctico'), ('Participación', 'Participación'), ('Tarea', 'Tarea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('nota', 'Nota'), ('sancion', 'Sanción'), ('inasistencia', 'Inasistencia'), ('mensaje', 'Mensaje'), ('evento', 'Evento'), ('otro', 'Otro')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='sancion',
            name='tipo',
            field=models.CharField(choices=[('Amonestación', 'Amonestación'), ('Llamado de atención', 'Llamado de atención'), ('Suspensión', 'Suspensión')], default='Amonestación', max_length=50),
        ),
    ]
