# Generated by Codex on 2026-03-06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calificaciones", "0033_alter_asistencia_tipo_asistencia_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertaAcademica",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("materia", models.CharField(db_index=True, max_length=50)),
                ("cuatrimestre", models.IntegerField(blank=True, db_index=True, null=True)),
                ("severidad", models.IntegerField(db_index=True)),
                ("riesgo_ponderado", models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ("triggers", models.JSONField(blank=True, default=dict)),
                ("ventana_desde", models.DateField(blank=True, null=True)),
                ("ventana_hasta", models.DateField(blank=True, null=True)),
                ("fecha_evento", models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ("estado", models.CharField(choices=[("activa", "Activa"), ("cerrada", "Cerrada")], db_index=True, default="activa", max_length=20)),
                ("creada_en", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("alumno", models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, related_name="alertas_academicas", to="calificaciones.alumno")),
                ("creada_por", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="alertas_creadas", to=settings.AUTH_USER_MODEL)),
                ("nota_disparadora", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="alertas_disparadas", to="calificaciones.nota")),
            ],
            options={
                "ordering": ["-creada_en", "-id"],
                "indexes": [
                    models.Index(fields=["alumno", "materia", "creada_en"], name="calificacio_alumno__be278b_idx"),
                    models.Index(fields=["alumno", "materia", "cuatrimestre"], name="calificacio_alumno__a4cd8f_idx"),
                ],
            },
        ),
    ]
