# Generated by Codex on 2026-03-06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calificaciones", "0034_alertaacademica"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertaInasistencia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("curso", models.CharField(db_index=True, max_length=20)),
                ("tipo_asistencia", models.CharField(db_index=True, default="clases", max_length=20)),
                ("motivo", models.CharField(choices=[("AUSENCIAS_CONSECUTIVAS", "Ausencias consecutivas")], db_index=True, max_length=40)),
                ("severidad", models.IntegerField(db_index=True, default=1)),
                ("valor_actual", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("umbral", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("estado", models.CharField(choices=[("activa", "Activa"), ("cerrada", "Cerrada")], db_index=True, default="activa", max_length=20)),
                ("fecha_evento", models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ("detalle", models.JSONField(blank=True, default=dict)),
                ("creada_en", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("cerrada_en", models.DateTimeField(blank=True, null=True)),
                ("alumno", models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, related_name="alertas_inasistencia", to="calificaciones.alumno")),
                ("asistencia_disparadora", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="alertas_inasistencia_disparadas", to="calificaciones.asistencia")),
                ("creada_por", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="alertas_inasistencia_creadas", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-creada_en", "-id"],
                "indexes": [
                    models.Index(fields=["alumno", "motivo", "estado"], name="calificacio_alumno__57d601_idx"),
                    models.Index(fields=["curso", "estado", "creada_en"], name="calificacio_curso_7d9006_idx"),
                ],
            },
        ),
    ]

