# Generated by Codex on 2026-03-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calificaciones", "0035_alertainasistencia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertainasistencia",
            name="motivo",
            field=models.CharField(
                choices=[
                    ("AUSENCIAS_CONSECUTIVAS", "Ausencias consecutivas"),
                    ("FALTAS_ACUMULADAS", "Faltas acumuladas"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
    ]

