# Generated by Django 5.1.7 on 2026-03-26 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0041_create_directivos_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Colegio',
                'verbose_name_plural': 'Colegios',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.RenameIndex(
            model_name='alertaacademica',
            new_name='calificacio_alumno__d50f79_idx',
            old_name='calificacio_alumno__be278b_idx',
        ),
        migrations.RenameIndex(
            model_name='alertaacademica',
            new_name='calificacio_alumno__56c497_idx',
            old_name='calificacio_alumno__a4cd8f_idx',
        ),
        migrations.RenameIndex(
            model_name='alertainasistencia',
            new_name='calificacio_alumno__8e70ce_idx',
            old_name='calificacio_alumno__57d601_idx',
        ),
        migrations.RenameIndex(
            model_name='alertainasistencia',
            new_name='calificacio_curso_8ccfc1_idx',
            old_name='calificacio_curso_7d9006_idx',
        ),
        migrations.RenameIndex(
            model_name='asistencia',
            new_name='calificacio_alumno__3e0bd7_idx',
            old_name='calif_asis_tipo_pres_idx',
        ),
        migrations.RenameIndex(
            model_name='mensaje',
            new_name='calificacio_destina_dd79f8_idx',
            old_name='calif_msg_dlf_idx',
        ),
        migrations.RenameIndex(
            model_name='mensaje',
            new_name='calificacio_destina_dcb0bf_idx',
            old_name='calif_msg_df_idx',
        ),
        migrations.RenameIndex(
            model_name='mensaje',
            new_name='calificacio_remiten_033ae9_idx',
            old_name='calif_msg_rf_idx',
        ),
        migrations.RenameIndex(
            model_name='notificacion',
            new_name='calificacio_destina_aa006c_idx',
            old_name='calif_notif_dlcr_idx',
        ),
        migrations.RenameIndex(
            model_name='notificacion',
            new_name='calificacio_destina_8954b5_idx',
            old_name='calif_notif_dcr_idx',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='curso',
            field=models.CharField(choices=[('1A', '1A'), ('1B', '1B'), ('2A', '2A'), ('2B', '2B'), ('3A', '3A'), ('3B', '3B'), ('4ECO', '4ECO'), ('4NAT', '4NAT'), ('5ECO', '5ECO'), ('5NAT', '5NAT'), ('6ECO', '6ECO'), ('6NAT', '6NAT')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='evento',
            name='curso',
            field=models.CharField(choices=[('1A', '1A'), ('1B', '1B'), ('2A', '2A'), ('2B', '2B'), ('3A', '3A'), ('3B', '3B'), ('4ECO', '4ECO'), ('4NAT', '4NAT'), ('5ECO', '5ECO'), ('5NAT', '5NAT'), ('6ECO', '6ECO'), ('6NAT', '6NAT')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='nota',
            name='materia',
            field=models.CharField(choices=[('Lengua', 'Lengua'), ('Matemática', 'Matemática'), ('Ciencias', 'Ciencias'), ('Historia', 'Historia'), ('Geografía', 'Geografía'), ('Inglés', 'Inglés'), ('Educación Física', 'Educación Física'), ('Música', 'Música'), ('Plástica', 'Plástica'), ('Catequesis', 'Catequesis'), ('Informática', 'Informática')], max_length=50),
        ),
        migrations.AlterField(
            model_name='nota',
            name='tipo',
            field=models.CharField(choices=[('Examen', 'Examen'), ('Trabajo Práctico', 'Trabajo Práctico'), ('Participación', 'Participación'), ('Tarea', 'Tarea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='preceptorcurso',
            name='curso',
            field=models.CharField(choices=[('1A', '1A'), ('1B', '1B'), ('2A', '2A'), ('2B', '2B'), ('3A', '3A'), ('3B', '3B'), ('4ECO', '4ECO'), ('4NAT', '4NAT'), ('5ECO', '5ECO'), ('5NAT', '5NAT'), ('6ECO', '6ECO'), ('6NAT', '6NAT')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profesorcurso',
            name='curso',
            field=models.CharField(choices=[('1A', '1A'), ('1B', '1B'), ('2A', '2A'), ('2B', '2B'), ('3A', '3A'), ('3B', '3B'), ('4ECO', '4ECO'), ('4NAT', '4NAT'), ('5ECO', '5ECO'), ('5NAT', '5NAT'), ('6ECO', '6ECO'), ('6NAT', '6NAT')], db_index=True, max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='preceptorcurso',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='profesorcurso',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='alertaacademica',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alertas_academicas', to='calificaciones.school'),
        ),
        migrations.AddField(
            model_name='alertainasistencia',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alertas_inasistencias', to='calificaciones.school'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alumnos', to='calificaciones.school'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='calificaciones.school'),
        ),
        migrations.AddField(
            model_name='comunicado',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comunicados', to='calificaciones.school'),
        ),
        migrations.AddField(
            model_name='evento',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='calificaciones.school'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mensajes', to='calificaciones.school'),
        ),
        migrations.AddField(
            model_name='nota',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='calificaciones.school'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones', to='calificaciones.school'),
        ),
        migrations.AddField(
            model_name='preceptorcurso',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preceptor_asignaciones', to='calificaciones.school'),
        ),
        migrations.AddField(
            model_name='profesorcurso',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profesor_asignaciones', to='calificaciones.school'),
        ),
        migrations.AddField(
            model_name='sancion',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sanciones', to='calificaciones.school'),
        ),
        migrations.AlterUniqueTogether(
            name='preceptorcurso',
            unique_together={('preceptor', 'school', 'curso')},
        ),
        migrations.AlterUniqueTogether(
            name='profesorcurso',
            unique_together={('profesor', 'school', 'curso')},
        ),
    ]
