# Generated by Django 5.1.7 on 2026-03-26 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0043_backfill_school_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='calificaciones.school')),
            ],
            options={
                'verbose_name': 'Curso por colegio',
                'verbose_name_plural': 'Cursos por colegio',
                'ordering': ['school_id', 'sort_order', 'name', 'id'],
                'indexes': [models.Index(fields=['school', 'is_active', 'sort_order'], name='calificacio_school__c56232_idx'), models.Index(fields=['school', 'code'], name='calificacio_school__7304c5_idx')],
                'constraints': [models.UniqueConstraint(fields=('school', 'code'), name='unique_school_course_code')],
            },
        ),
    ]
