# Generated by Django 5.1.7 on 2026-03-26 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0045_backfill_schoolcourse_catalog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preceptorcurso',
            options={'verbose_name': 'Asignaci\u00f3n de curso a preceptor', 'verbose_name_plural': 'Asignaciones de cursos a preceptores'},
        ),
        migrations.AlterModelOptions(
            name='profesorcurso',
            options={'verbose_name': 'Asignaci\u00f3n de curso a profesor', 'verbose_name_plural': 'Asignaciones de cursos a profesores'},
        ),
        migrations.AddField(
            model_name='alumno',
            name='school_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos', to='calificaciones.schoolcourse'),
        ),
        migrations.AddField(
            model_name='preceptorcurso',
            name='school_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preceptor_asignaciones', to='calificaciones.schoolcourse'),
        ),
        migrations.AddField(
            model_name='profesorcurso',
            name='school_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profesor_asignaciones', to='calificaciones.schoolcourse'),
        ),
    ]
