# Generated by Django 5.1.7 on 2026-03-27 04:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0049_rename_default_school_slug_to_escuela_itnova'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='id_alumno',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AddConstraint(
            model_name='alumno',
            constraint=models.UniqueConstraint(fields=('school', 'id_alumno'), name='unique_alumno_school_legajo'),
        ),
    ]
