# Generated by Django 5.1.7 on 2026-04-07 15:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0060_rename_default_school_slug_to_tecnova'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='nota',
            index=models.Index(fields=['alumno', 'materia', 'fecha'], name='calificacio_alumno__544098_idx'),
        ),
    ]
