# Generated by Django 5.1.7 on 2026-04-21 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0064_mensaje_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='leido_en',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
