# Generated by Django 5.1.7 on 2026-04-21 03:09

from django.db import migrations, models


TABLE_NAME = "calificaciones_mensaje"
COLUMN_NAME = "leido_en"
INDEX_NAME = "calificaciones_mensaje_leido_en_idx"


def _column_exists(schema_editor):
    with schema_editor.connection.cursor() as cursor:
        columns = schema_editor.connection.introspection.get_table_description(cursor, TABLE_NAME)
    return any(column.name == COLUMN_NAME for column in columns)


def _index_exists(schema_editor):
    with schema_editor.connection.cursor() as cursor:
        constraints = schema_editor.connection.introspection.get_constraints(cursor, TABLE_NAME)
    return INDEX_NAME in constraints


def ensure_leido_en_column(apps, schema_editor):
    Mensaje = apps.get_model("calificaciones", "Mensaje")
    if not _column_exists(schema_editor):
        field = models.DateTimeField(null=True, blank=True)
        field.set_attributes_from_name(COLUMN_NAME)
        schema_editor.add_field(Mensaje, field)

    if not _index_exists(schema_editor):
        schema_editor.execute(f"CREATE INDEX {INDEX_NAME} ON {TABLE_NAME} ({COLUMN_NAME})")


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0064_mensaje_alumno'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    ensure_leido_en_column,
                    reverse_code=migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='mensaje',
                    name='leido_en',
                    field=models.DateTimeField(blank=True, db_index=True, null=True),
                ),
            ],
        ),
    ]
