# Generated by Django 5.2.16 on 2026-10-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0096_create_eoe_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='es_ppi',
            field=models.BooleanField(default=False, help_text='El estudiante tiene acompañamiento psicopedagógico.', verbose_name='PPI'),
        ),
    ]
