# Generated by Django 5.2.16 on 2026-10-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0099_create_integracion_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='recordatorio_resuelto_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='ultimo_recordatorio_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
