# Generated by Django 5.2.16 on 2026-10-08 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0100_message_reminders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ppidocument',
            name='requiere_firma',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ppidocument',
            name='sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='ppidocument',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ppidocument',
            name='version_anterior',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='version_siguiente', to='calificaciones.ppidocument'),
        ),
        migrations.CreateModel(
            name='PpiDocumentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_docente', models.CharField(max_length=255)),
                ('consultado_en', models.DateTimeField(blank=True, null=True)),
                ('firmado_en', models.DateTimeField(blank=True, null=True)),
                ('declaracion', models.CharField(blank=True, max_length=255)),
                ('ultimo_recordatorio_en', models.DateTimeField(blank=True, null=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='calificaciones.ppidocument')),
            ],
            options={
                'ordering': ['nombre_docente', 'id'],
                'constraints': [models.UniqueConstraint(fields=('documento', 'docente'), name='unique_ppi_document_teacher')],
            },
        ),
    ]
